/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotModel/msg/ArbiterConfig.msg */
#ifndef RE2ROBOTMODEL_MESSAGE_ARBITERCONFIG_H
#define RE2ROBOTMODEL_MESSAGE_ARBITERCONFIG_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace re2robotModel
{
template <class ContainerAllocator>
struct ArbiterConfig_ : public ros::Message
{
  typedef ArbiterConfig_<ContainerAllocator> Type;

  ArbiterConfig_()
  : type()
  , updateIntervalS(0.0)
  , initialController()
  {
  }

  ArbiterConfig_(const ContainerAllocator& _alloc)
  : type(_alloc)
  , updateIntervalS(0.0)
  , initialController(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  type;

  typedef float _updateIntervalS_type;
  float updateIntervalS;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _initialController_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  initialController;


private:
  static const char* __s_getDataType_() { return "re2robotModel/ArbiterConfig"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "16d15c6c4f109996d0d7cf619c2c571b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#common\n\
string type\n\
float32 updateIntervalS\n\
\n\
#control arbiter\n\
string initialController\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, updateIntervalS);
    ros::serialization::serialize(stream, initialController);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, updateIntervalS);
    ros::serialization::deserialize(stream, initialController);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(updateIntervalS);
    size += ros::serialization::serializationLength(initialController);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::ArbiterConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::ArbiterConfig_<ContainerAllocator>  const> ConstPtr;
}; // struct ArbiterConfig
typedef  ::re2robotModel::ArbiterConfig_<std::allocator<void> > ArbiterConfig;

typedef boost::shared_ptr< ::re2robotModel::ArbiterConfig> ArbiterConfigPtr;
typedef boost::shared_ptr< ::re2robotModel::ArbiterConfig const> ArbiterConfigConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::re2robotModel::ArbiterConfig_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::re2robotModel::ArbiterConfig_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace re2robotModel

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::ArbiterConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "16d15c6c4f109996d0d7cf619c2c571b";
  }

  static const char* value(const  ::re2robotModel::ArbiterConfig_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x16d15c6c4f109996ULL;
  static const uint64_t static_value2 = 0xd0d7cf619c2c571bULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::ArbiterConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/ArbiterConfig";
  }

  static const char* value(const  ::re2robotModel::ArbiterConfig_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::ArbiterConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#common\n\
string type\n\
float32 updateIntervalS\n\
\n\
#control arbiter\n\
string initialController\n\
";
  }

  static const char* value(const  ::re2robotModel::ArbiterConfig_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::ArbiterConfig_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.type);
    stream.next(m.updateIntervalS);
    stream.next(m.initialController);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ArbiterConfig_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::re2robotModel::ArbiterConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::re2robotModel::ArbiterConfig_<ContainerAllocator> & v) 
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "updateIntervalS: ";
    Printer<float>::stream(s, indent + "  ", v.updateIntervalS);
    s << indent << "initialController: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.initialController);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RE2ROBOTMODEL_MESSAGE_ARBITERCONFIG_H

