import glob
import os

env = Environment()

env['SHOBJSUFFIX'] = '.oss'

env.Append(CPPPATH = env.Split('''
    #
    ext/tinyxml
    /usr/include/python2.6 
    /usr/local/include/OGRE
    /usr/local/include/OIS
    /usr/local/include/CEGUI
    /usr/local/include/bullet
    '''))
    
env.Append(LIBS = env.Split('''
    python2.6
    boost_python-mt-py26
    boost_filesystem-mt
    CEGUIBase
    CEGUIOgreRenderer
    OgreMain
    OIS
    bulletdynamics
    bulletcollision
    bulletmath
    '''))
    
env.Append(LIBPATH = env.Split('''
    /usr/local/lib
    '''))

def enumerateFiles(path = "."):
    files = glob.glob("%s/*" % path)
    return sum(map(enumerateFiles,filter(os.path.isdir,files)),filter(os.path.isfile,files))

files = enumerateFiles()

src = filter(lambda file: file.endswith(".cpp"),files)

mainSrc = filter(lambda file: 'main' in file.lower(), src)
libSrc = filter(lambda file: file not in mainSrc, src)

lib = env.SharedLibrary('gge',libSrc)

apps = map(lambda file: env.Program(file[:file.rfind('.')].lstrip('./').replace('/','.'), [file,lib]), mainSrc)
