(cl:defpackage re2robotModel-srv
  (:use )
  (:export
   "REMOVEARBITER"
   "<REMOVEARBITER-REQUEST>"
   "REMOVEARBITER-REQUEST"
   "<REMOVEARBITER-RESPONSE>"
   "REMOVEARBITER-RESPONSE"
   "ADDTRANSMISSION"
   "<ADDTRANSMISSION-REQUEST>"
   "ADDTRANSMISSION-REQUEST"
   "<ADDTRANSMISSION-RESPONSE>"
   "ADDTRANSMISSION-RESPONSE"
   "REMOVETRANSMISSION"
   "<REMOVETRANSMISSION-REQUEST>"
   "REMOVETRANSMISSION-REQUEST"
   "<REMOVETRANSMISSION-RESPONSE>"
   "REMOVETRANSMISSION-RESPONSE"
   "ADDARBITER"
   "<ADDARBITER-REQUEST>"
   "ADDARBITER-REQUEST"
   "<ADDARBITER-RESPONSE>"
   "ADDARBITER-RESPONSE"
  ))

