Import("env")

_env = env

env = env.Clone()
fhe = env.Install("#bin",[env.SharedLibrary("fhe", env.Glob("*.cpp") + env.Glob("tinyxml/*.cpp")),"PyNode.py"])
env.Depends(fhe,"ext")

_env.Append(LIBS = fhe[0].name)
