Import("env")

deps = """ sudo apt-get install 
    build-essential autoconf automake libtool libzzip-dev libxt-dev libxaw-headers libxxf86vm-dev 
    libxrandr-dev libfreeimage-dev nvidia-cg-toolkit checkinstall libfreetype6-dev libpcre3-dev libdevil-dev libxaw7-dev 
    libopenexr-dev libtiff-dev libglade2-dev libglademm-2.4-dev """

tarfile = "ogre-v1-6-3.tar.bz2"
dl = "http://downloads.sourceforge.net/project/ogre/ogre/1.6.3/%s" % tarfile
env.Command(tarfile,None,"cd ext/ogre && wget %s" % dl)
env.NoClean(tarfile)
env.Command("ogre/configure",tarfile,"cd ext/ogre && tar xjf %s" % tarfile)
env.Command("ogre/Makefile","ogre/configure","cd ext/ogre/ogre && aclocal && ./bootstrap && ./configure")

libs = ["ogre/OgreMain/src/.libs/libOgreMain.so","ogre/OgreMain/src/.libs/libOgreMain-1.6.3.so"]
env.Command(libs,"ogre/Makefile","cd ext/ogre/ogre && make -j 4")

ilibs = env.Install("#bin",libs)

env.Append(CPPPATH = env.Dir("ogre/OgreMain/include").abspath)
env.Append(LIBS = ilibs)
