"""autogenerated by genmsg_py from DriverConfig.msg. Do not edit."""
import roslib.message
import struct

import re2robotDriver.msg

class DriverConfig(roslib.message.Message):
  _md5sum = "eeb8e90567be2610059b20481b8a260e"
  _type = "re2robotDriver/DriverConfig"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """DriveConfig[] drives
================================================================================
MSG: re2robotDriver/DriveConfig
#Drive
string name
string type
float32 updateIntervalS
float32 cmdTimeoutS
float32 maxVelocity
float32 minPosition
float32 maxPosition

#SimDrive
float32 initialPosition
float32 positionPGain
float32 positionDGain
float32 velocityTimeToTargetS
"""
  __slots__ = ['drives']
  _slot_types = ['re2robotDriver/DriveConfig[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       drives
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(DriverConfig, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.drives is None:
        self.drives = []
    else:
      self.drives = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      length = len(self.drives)
      buff.write(_struct_I.pack(length))
      for val1 in self.drives:
        _x = val1.name
        length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.type
        length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_9f.pack(_x.updateIntervalS, _x.cmdTimeoutS, _x.maxVelocity, _x.minPosition, _x.maxPosition, _x.initialPosition, _x.positionPGain, _x.positionDGain, _x.velocityTimeToTargetS))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.drives = []
      for i in xrange(0, length):
        val1 = re2robotDriver.msg.DriveConfig()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.type = str[start:end]
        _x = val1
        start = end
        end += 36
        (_x.updateIntervalS, _x.cmdTimeoutS, _x.maxVelocity, _x.minPosition, _x.maxPosition, _x.initialPosition, _x.positionPGain, _x.positionDGain, _x.velocityTimeToTargetS,) = _struct_9f.unpack(str[start:end])
        self.drives.append(val1)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      length = len(self.drives)
      buff.write(_struct_I.pack(length))
      for val1 in self.drives:
        _x = val1.name
        length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.type
        length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_9f.pack(_x.updateIntervalS, _x.cmdTimeoutS, _x.maxVelocity, _x.minPosition, _x.maxPosition, _x.initialPosition, _x.positionPGain, _x.positionDGain, _x.velocityTimeToTargetS))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.drives = []
      for i in xrange(0, length):
        val1 = re2robotDriver.msg.DriveConfig()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.type = str[start:end]
        _x = val1
        start = end
        end += 36
        (_x.updateIntervalS, _x.cmdTimeoutS, _x.maxVelocity, _x.minPosition, _x.maxPosition, _x.initialPosition, _x.positionPGain, _x.positionDGain, _x.velocityTimeToTargetS,) = _struct_9f.unpack(str[start:end])
        self.drives.append(val1)
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_9f = struct.Struct("<9f")
