Import("env")

fheenv = env.Clone()
fhe = fheenv.Install("#bin",fheenv.SharedLibrary("fhe", fheenv.Glob("*.cpp") + fheenv.Glob("tinyxml/*.cpp")))
fheenv.Depends(fhe,"ext")
fheenv.Install("#bin","PyNode.py")

env.Append(LIBS = "fhe")
