/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotDriver/msg/DriveConfig.msg */
#ifndef RE2ROBOTDRIVER_MESSAGE_DRIVECONFIG_H
#define RE2ROBOTDRIVER_MESSAGE_DRIVECONFIG_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace re2robotDriver
{
template <class ContainerAllocator>
struct DriveConfig_ : public ros::Message
{
  typedef DriveConfig_<ContainerAllocator> Type;

  DriveConfig_()
  : name()
  , type()
  , updateIntervalS(0.0)
  , cmdTimeoutS(0.0)
  , maxVelocity(0.0)
  , minPosition(0.0)
  , maxPosition(0.0)
  , initialPosition(0.0)
  , positionPGain(0.0)
  , positionDGain(0.0)
  , velocityTimeToTargetS(0.0)
  {
  }

  DriveConfig_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , type(_alloc)
  , updateIntervalS(0.0)
  , cmdTimeoutS(0.0)
  , maxVelocity(0.0)
  , minPosition(0.0)
  , maxPosition(0.0)
  , initialPosition(0.0)
  , positionPGain(0.0)
  , positionDGain(0.0)
  , velocityTimeToTargetS(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  type;

  typedef float _updateIntervalS_type;
  float updateIntervalS;

  typedef float _cmdTimeoutS_type;
  float cmdTimeoutS;

  typedef float _maxVelocity_type;
  float maxVelocity;

  typedef float _minPosition_type;
  float minPosition;

  typedef float _maxPosition_type;
  float maxPosition;

  typedef float _initialPosition_type;
  float initialPosition;

  typedef float _positionPGain_type;
  float positionPGain;

  typedef float _positionDGain_type;
  float positionDGain;

  typedef float _velocityTimeToTargetS_type;
  float velocityTimeToTargetS;


private:
  static const char* __s_getDataType_() { return "re2robotDriver/DriveConfig"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "7739876033e4c5d57efaa789aba3f14f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#Drive\n\
string name\n\
string type\n\
float32 updateIntervalS\n\
float32 cmdTimeoutS\n\
float32 maxVelocity\n\
float32 minPosition\n\
float32 maxPosition\n\
\n\
#SimDrive\n\
float32 initialPosition\n\
float32 positionPGain\n\
float32 positionDGain\n\
float32 velocityTimeToTargetS\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, name);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, updateIntervalS);
    ros::serialization::serialize(stream, cmdTimeoutS);
    ros::serialization::serialize(stream, maxVelocity);
    ros::serialization::serialize(stream, minPosition);
    ros::serialization::serialize(stream, maxPosition);
    ros::serialization::serialize(stream, initialPosition);
    ros::serialization::serialize(stream, positionPGain);
    ros::serialization::serialize(stream, positionDGain);
    ros::serialization::serialize(stream, velocityTimeToTargetS);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, name);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, updateIntervalS);
    ros::serialization::deserialize(stream, cmdTimeoutS);
    ros::serialization::deserialize(stream, maxVelocity);
    ros::serialization::deserialize(stream, minPosition);
    ros::serialization::deserialize(stream, maxPosition);
    ros::serialization::deserialize(stream, initialPosition);
    ros::serialization::deserialize(stream, positionPGain);
    ros::serialization::deserialize(stream, positionDGain);
    ros::serialization::deserialize(stream, velocityTimeToTargetS);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(name);
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(updateIntervalS);
    size += ros::serialization::serializationLength(cmdTimeoutS);
    size += ros::serialization::serializationLength(maxVelocity);
    size += ros::serialization::serializationLength(minPosition);
    size += ros::serialization::serializationLength(maxPosition);
    size += ros::serialization::serializationLength(initialPosition);
    size += ros::serialization::serializationLength(positionPGain);
    size += ros::serialization::serializationLength(positionDGain);
    size += ros::serialization::serializationLength(velocityTimeToTargetS);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotDriver::DriveConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotDriver::DriveConfig_<ContainerAllocator>  const> ConstPtr;
}; // struct DriveConfig
typedef  ::re2robotDriver::DriveConfig_<std::allocator<void> > DriveConfig;

typedef boost::shared_ptr< ::re2robotDriver::DriveConfig> DriveConfigPtr;
typedef boost::shared_ptr< ::re2robotDriver::DriveConfig const> DriveConfigConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::re2robotDriver::DriveConfig_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::re2robotDriver::DriveConfig_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace re2robotDriver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotDriver::DriveConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7739876033e4c5d57efaa789aba3f14f";
  }

  static const char* value(const  ::re2robotDriver::DriveConfig_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7739876033e4c5d5ULL;
  static const uint64_t static_value2 = 0x7efaa789aba3f14fULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotDriver::DriveConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotDriver/DriveConfig";
  }

  static const char* value(const  ::re2robotDriver::DriveConfig_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotDriver::DriveConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Drive\n\
string name\n\
string type\n\
float32 updateIntervalS\n\
float32 cmdTimeoutS\n\
float32 maxVelocity\n\
float32 minPosition\n\
float32 maxPosition\n\
\n\
#SimDrive\n\
float32 initialPosition\n\
float32 positionPGain\n\
float32 positionDGain\n\
float32 velocityTimeToTargetS\n\
";
  }

  static const char* value(const  ::re2robotDriver::DriveConfig_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotDriver::DriveConfig_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.type);
    stream.next(m.updateIntervalS);
    stream.next(m.cmdTimeoutS);
    stream.next(m.maxVelocity);
    stream.next(m.minPosition);
    stream.next(m.maxPosition);
    stream.next(m.initialPosition);
    stream.next(m.positionPGain);
    stream.next(m.positionDGain);
    stream.next(m.velocityTimeToTargetS);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DriveConfig_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::re2robotDriver::DriveConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::re2robotDriver::DriveConfig_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "updateIntervalS: ";
    Printer<float>::stream(s, indent + "  ", v.updateIntervalS);
    s << indent << "cmdTimeoutS: ";
    Printer<float>::stream(s, indent + "  ", v.cmdTimeoutS);
    s << indent << "maxVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.maxVelocity);
    s << indent << "minPosition: ";
    Printer<float>::stream(s, indent + "  ", v.minPosition);
    s << indent << "maxPosition: ";
    Printer<float>::stream(s, indent + "  ", v.maxPosition);
    s << indent << "initialPosition: ";
    Printer<float>::stream(s, indent + "  ", v.initialPosition);
    s << indent << "positionPGain: ";
    Printer<float>::stream(s, indent + "  ", v.positionPGain);
    s << indent << "positionDGain: ";
    Printer<float>::stream(s, indent + "  ", v.positionDGain);
    s << indent << "velocityTimeToTargetS: ";
    Printer<float>::stream(s, indent + "  ", v.velocityTimeToTargetS);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RE2ROBOTDRIVER_MESSAGE_DRIVECONFIG_H

