/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotDriver/msg/DriveCmd.msg */
#ifndef RE2ROBOTDRIVER_MESSAGE_DRIVECMD_H
#define RE2ROBOTDRIVER_MESSAGE_DRIVECMD_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace re2robotDriver
{
template <class ContainerAllocator>
struct DriveCmd_ : public ros::Message
{
  typedef DriveCmd_<ContainerAllocator> Type;

  DriveCmd_()
  : mode(0)
  , cmd(0.0)
  {
  }

  DriveCmd_(const ContainerAllocator& _alloc)
  : mode(0)
  , cmd(0.0)
  {
  }

  typedef uint8_t _mode_type;
  uint8_t mode;

  typedef float _cmd_type;
  float cmd;

  enum { MODE_EFFORT = 1 };
  enum { MODE_VELOCITY = 2 };
  enum { MODE_POSITION = 3 };

private:
  static const char* __s_getDataType_() { return "re2robotDriver/DriveCmd"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3af6dabffd29e01e37500e9a7f5f0bdd"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 MODE_EFFORT = 1\n\
uint8 MODE_VELOCITY = 2\n\
uint8 MODE_POSITION = 3\n\
\n\
uint8 mode\n\
float32 cmd\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, mode);
    ros::serialization::serialize(stream, cmd);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, mode);
    ros::serialization::deserialize(stream, cmd);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(mode);
    size += ros::serialization::serializationLength(cmd);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotDriver::DriveCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotDriver::DriveCmd_<ContainerAllocator>  const> ConstPtr;
}; // struct DriveCmd
typedef  ::re2robotDriver::DriveCmd_<std::allocator<void> > DriveCmd;

typedef boost::shared_ptr< ::re2robotDriver::DriveCmd> DriveCmdPtr;
typedef boost::shared_ptr< ::re2robotDriver::DriveCmd const> DriveCmdConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::re2robotDriver::DriveCmd_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::re2robotDriver::DriveCmd_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace re2robotDriver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotDriver::DriveCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3af6dabffd29e01e37500e9a7f5f0bdd";
  }

  static const char* value(const  ::re2robotDriver::DriveCmd_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3af6dabffd29e01eULL;
  static const uint64_t static_value2 = 0x37500e9a7f5f0bddULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotDriver::DriveCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotDriver/DriveCmd";
  }

  static const char* value(const  ::re2robotDriver::DriveCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotDriver::DriveCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 MODE_EFFORT = 1\n\
uint8 MODE_VELOCITY = 2\n\
uint8 MODE_POSITION = 3\n\
\n\
uint8 mode\n\
float32 cmd\n\
";
  }

  static const char* value(const  ::re2robotDriver::DriveCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::re2robotDriver::DriveCmd_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotDriver::DriveCmd_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.mode);
    stream.next(m.cmd);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DriveCmd_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::re2robotDriver::DriveCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::re2robotDriver::DriveCmd_<ContainerAllocator> & v) 
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "cmd: ";
    Printer<float>::stream(s, indent + "  ", v.cmd);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RE2ROBOTDRIVER_MESSAGE_DRIVECMD_H

