env = Environment()

env.ParseConfig( 'pkg-config --cflags --libs glib-2.0 gmodule-2.0' )
env.Append( CPPPATH = [ '#' ] )
env.Append( RPATH = [ env.Dir( '#' ).abspath ] )
env.Append( CPPFLAGS = [ '-g', '-Wall', '-Werror' ] )

lib_fhe = env.SharedLibrary( 'fhe', env.Glob( 'fhe/*.c' ) )

env = env.Clone()
env.Append( LIBS = [ lib_fhe ] )

test_common = env.SharedLibrary( 'test_common', env.Glob( 'test/common/*.c' ) )

env = env.Clone()
env.Append( LIBS = [ test_common, 'gtest' ] )

test_srcs = env.Glob( 'test/*.cpp' )
for test_src in test_srcs:
    test_exe = env.Program( test_src )
    test_name = str( test_exe[0] )
    env.Command( test_name + '.out', test_exe, test_name )
