/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotModel/srv/RemoveArbiter.srv */
#ifndef RE2ROBOTMODEL_SERVICE_REMOVEARBITER_H
#define RE2ROBOTMODEL_SERVICE_REMOVEARBITER_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace re2robotModel
{
template <class ContainerAllocator>
struct RemoveArbiterRequest_ : public ros::Message
{
  typedef RemoveArbiterRequest_<ContainerAllocator> Type;

  RemoveArbiterRequest_()
  : type()
  {
  }

  RemoveArbiterRequest_(const ContainerAllocator& _alloc)
  : type(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  type;


private:
  static const char* __s_getDataType_() { return "re2robotModel/RemoveArbiterRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "dc67331de85cf97091b7d45e5c64ab75"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "6f79030b38c16e3be13c8c4e4b634640"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string type\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, type);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, type);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(type);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct RemoveArbiterRequest
typedef  ::re2robotModel::RemoveArbiterRequest_<std::allocator<void> > RemoveArbiterRequest;

typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterRequest> RemoveArbiterRequestPtr;
typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterRequest const> RemoveArbiterRequestConstPtr;


template <class ContainerAllocator>
struct RemoveArbiterResponse_ : public ros::Message
{
  typedef RemoveArbiterResponse_<ContainerAllocator> Type;

  RemoveArbiterResponse_()
  : success(false)
  {
  }

  RemoveArbiterResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "re2robotModel/RemoveArbiterResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "6f79030b38c16e3be13c8c4e4b634640"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct RemoveArbiterResponse
typedef  ::re2robotModel::RemoveArbiterResponse_<std::allocator<void> > RemoveArbiterResponse;

typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterResponse> RemoveArbiterResponsePtr;
typedef boost::shared_ptr< ::re2robotModel::RemoveArbiterResponse const> RemoveArbiterResponseConstPtr;

struct RemoveArbiter
{

typedef RemoveArbiterRequest Request;
typedef RemoveArbiterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct RemoveArbiter
} // namespace re2robotModel

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dc67331de85cf97091b7d45e5c64ab75";
  }

  static const char* value(const  ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdc67331de85cf970ULL;
  static const uint64_t static_value2 = 0x91b7d45e5c64ab75ULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveArbiterRequest";
  }

  static const char* value(const  ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string type\n\
\n\
";
  }

  static const char* value(const  ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveArbiterResponse";
  }

  static const char* value(const  ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::RemoveArbiterRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.type);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RemoveArbiterRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::RemoveArbiterResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RemoveArbiterResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<re2robotModel::RemoveArbiter> {
  static const char* value() 
  {
    return "6f79030b38c16e3be13c8c4e4b634640";
  }

  static const char* value(const re2robotModel::RemoveArbiter&) { return value(); } 
};

template<>
struct DataType<re2robotModel::RemoveArbiter> {
  static const char* value() 
  {
    return "re2robotModel/RemoveArbiter";
  }

  static const char* value(const re2robotModel::RemoveArbiter&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re2robotModel::RemoveArbiterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f79030b38c16e3be13c8c4e4b634640";
  }

  static const char* value(const re2robotModel::RemoveArbiterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re2robotModel::RemoveArbiterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveArbiter";
  }

  static const char* value(const re2robotModel::RemoveArbiterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f79030b38c16e3be13c8c4e4b634640";
  }

  static const char* value(const re2robotModel::RemoveArbiterResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re2robotModel::RemoveArbiterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveArbiter";
  }

  static const char* value(const re2robotModel::RemoveArbiterResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RE2ROBOTMODEL_SERVICE_REMOVEARBITER_H

