env = Environment()

env.Append(CPPPATH = ["#", '/usr/include/python2.6'])
env.Append(LIBS = ['python2.6','boost_python-mt-py26'])
env.Append(LIBPATH = "#bin")

Export("env")

env.SConscript("ext/SConscript")
env.SConscript("fhe/SConscript")
env.SConscript("ogre/SConscript")
env.SConscript("test/SConscript")
