(cl:defpackage re2robotModel-msg
  (:use )
  (:export
   "<MODELCONFIG>"
   "MODELCONFIG"
   "<JOINTSTATE>"
   "JOINTSTATE"
   "<TRANSMISSIONCONFIG>"
   "TRANSMISSIONCONFIG"
   "<ARBITERCONFIG>"
   "ARBITERCONFIG"
   "<JOINTCMD>"
   "JOINTCMD"
   "<CONTROLARBITERSTATE>"
   "CONTROLARBITERSTATE"
   "<CONTROLARBITERCMD>"
   "CONTROLARBITERCMD"
  ))

