env = Environment()

env.Append(CPPPATH = ["#", '/usr/include/python2.6'])
env.Append(LIBS = ['python2.6','boost_python-mt-py26'])

Export("env")

core = env.SConscript("fhe/SConscript")

Export("core")

env.SConscript("test/SConscript")
