/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotModel/msg/JointState.msg */
#ifndef RE2ROBOTMODEL_MESSAGE_JOINTSTATE_H
#define RE2ROBOTMODEL_MESSAGE_JOINTSTATE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace re2robotModel
{
template <class ContainerAllocator>
struct JointState_ : public ros::Message
{
  typedef JointState_<ContainerAllocator> Type;

  JointState_()
  : header()
  , effort(0.0)
  , velocity(0.0)
  , position(0.0)
  {
  }

  JointState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , effort(0.0)
  , velocity(0.0)
  , position(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _effort_type;
  float effort;

  typedef float _velocity_type;
  float velocity;

  typedef float _position_type;
  float position;


private:
  static const char* __s_getDataType_() { return "re2robotModel/JointState"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "909dc10c76ab46e18fbc3e3be61d280d"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float32 effort\n\
float32 velocity\n\
float32 position\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, effort);
    ros::serialization::serialize(stream, velocity);
    ros::serialization::serialize(stream, position);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, effort);
    ros::serialization::deserialize(stream, velocity);
    ros::serialization::deserialize(stream, position);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(effort);
    size += ros::serialization::serializationLength(velocity);
    size += ros::serialization::serializationLength(position);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::JointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::JointState_<ContainerAllocator>  const> ConstPtr;
}; // struct JointState
typedef  ::re2robotModel::JointState_<std::allocator<void> > JointState;

typedef boost::shared_ptr< ::re2robotModel::JointState> JointStatePtr;
typedef boost::shared_ptr< ::re2robotModel::JointState const> JointStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::re2robotModel::JointState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::re2robotModel::JointState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace re2robotModel

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::JointState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "909dc10c76ab46e18fbc3e3be61d280d";
  }

  static const char* value(const  ::re2robotModel::JointState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x909dc10c76ab46e1ULL;
  static const uint64_t static_value2 = 0x8fbc3e3be61d280dULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::JointState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/JointState";
  }

  static const char* value(const  ::re2robotModel::JointState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::JointState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 effort\n\
float32 velocity\n\
float32 position\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::re2robotModel::JointState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::re2robotModel::JointState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::re2robotModel::JointState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::JointState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.effort);
    stream.next(m.velocity);
    stream.next(m.position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::re2robotModel::JointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::re2robotModel::JointState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "effort: ";
    Printer<float>::stream(s, indent + "  ", v.effort);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RE2ROBOTMODEL_MESSAGE_JOINTSTATE_H

