/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotModel/msg/TransmissionConfig.msg */
#ifndef RE2ROBOTMODEL_MESSAGE_TRANSMISSIONCONFIG_H
#define RE2ROBOTMODEL_MESSAGE_TRANSMISSIONCONFIG_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace re2robotModel
{
template <class ContainerAllocator>
struct TransmissionConfig_ : public ros::Message
{
  typedef TransmissionConfig_<ContainerAllocator> Type;

  TransmissionConfig_()
  : type()
  , drive()
  , joint()
  , timerIntervalS(0.0)
  {
  }

  TransmissionConfig_(const ContainerAllocator& _alloc)
  : type(_alloc)
  , drive(_alloc)
  , joint(_alloc)
  , timerIntervalS(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  type;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _drive_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  drive;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  joint;

  typedef float _timerIntervalS_type;
  float timerIntervalS;


private:
  static const char* __s_getDataType_() { return "re2robotModel/TransmissionConfig"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "6841c6455f157038b84358a2ff1b61d4"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string type\n\
string drive\n\
string joint\n\
float32 timerIntervalS\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, type);
    ros::serialization::serialize(stream, drive);
    ros::serialization::serialize(stream, joint);
    ros::serialization::serialize(stream, timerIntervalS);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, type);
    ros::serialization::deserialize(stream, drive);
    ros::serialization::deserialize(stream, joint);
    ros::serialization::deserialize(stream, timerIntervalS);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(type);
    size += ros::serialization::serializationLength(drive);
    size += ros::serialization::serializationLength(joint);
    size += ros::serialization::serializationLength(timerIntervalS);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::TransmissionConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::TransmissionConfig_<ContainerAllocator>  const> ConstPtr;
}; // struct TransmissionConfig
typedef  ::re2robotModel::TransmissionConfig_<std::allocator<void> > TransmissionConfig;

typedef boost::shared_ptr< ::re2robotModel::TransmissionConfig> TransmissionConfigPtr;
typedef boost::shared_ptr< ::re2robotModel::TransmissionConfig const> TransmissionConfigConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::re2robotModel::TransmissionConfig_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::re2robotModel::TransmissionConfig_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace re2robotModel

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::TransmissionConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6841c6455f157038b84358a2ff1b61d4";
  }

  static const char* value(const  ::re2robotModel::TransmissionConfig_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6841c6455f157038ULL;
  static const uint64_t static_value2 = 0xb84358a2ff1b61d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::TransmissionConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/TransmissionConfig";
  }

  static const char* value(const  ::re2robotModel::TransmissionConfig_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::TransmissionConfig_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string type\n\
string drive\n\
string joint\n\
float32 timerIntervalS\n\
";
  }

  static const char* value(const  ::re2robotModel::TransmissionConfig_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::TransmissionConfig_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.type);
    stream.next(m.drive);
    stream.next(m.joint);
    stream.next(m.timerIntervalS);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TransmissionConfig_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::re2robotModel::TransmissionConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::re2robotModel::TransmissionConfig_<ContainerAllocator> & v) 
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "drive: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.drive);
    s << indent << "joint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint);
    s << indent << "timerIntervalS: ";
    Printer<float>::stream(s, indent + "  ", v.timerIntervalS);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RE2ROBOTMODEL_MESSAGE_TRANSMISSIONCONFIG_H

