/* Auto-generated by genmsg_cpp for file /home/dave/ros/re2robot/re2robotModel/srv/RemoveTransmission.srv */
#ifndef RE2ROBOTMODEL_SERVICE_REMOVETRANSMISSION_H
#define RE2ROBOTMODEL_SERVICE_REMOVETRANSMISSION_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace re2robotModel
{
template <class ContainerAllocator>
struct RemoveTransmissionRequest_ : public ros::Message
{
  typedef RemoveTransmissionRequest_<ContainerAllocator> Type;

  RemoveTransmissionRequest_()
  : joint()
  {
  }

  RemoveTransmissionRequest_(const ContainerAllocator& _alloc)
  : joint(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  joint;


private:
  static const char* __s_getDataType_() { return "re2robotModel/RemoveTransmissionRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "23b081b5cb543c8335b9afac2f3e238c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "296066438feec30c8905d1fe1042a90b"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string joint\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, joint);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, joint);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(joint);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct RemoveTransmissionRequest
typedef  ::re2robotModel::RemoveTransmissionRequest_<std::allocator<void> > RemoveTransmissionRequest;

typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionRequest> RemoveTransmissionRequestPtr;
typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionRequest const> RemoveTransmissionRequestConstPtr;


template <class ContainerAllocator>
struct RemoveTransmissionResponse_ : public ros::Message
{
  typedef RemoveTransmissionResponse_<ContainerAllocator> Type;

  RemoveTransmissionResponse_()
  : success(false)
  {
  }

  RemoveTransmissionResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "re2robotModel/RemoveTransmissionResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "296066438feec30c8905d1fe1042a90b"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool success\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct RemoveTransmissionResponse
typedef  ::re2robotModel::RemoveTransmissionResponse_<std::allocator<void> > RemoveTransmissionResponse;

typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionResponse> RemoveTransmissionResponsePtr;
typedef boost::shared_ptr< ::re2robotModel::RemoveTransmissionResponse const> RemoveTransmissionResponseConstPtr;

struct RemoveTransmission
{

typedef RemoveTransmissionRequest Request;
typedef RemoveTransmissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct RemoveTransmission
} // namespace re2robotModel

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "23b081b5cb543c8335b9afac2f3e238c";
  }

  static const char* value(const  ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x23b081b5cb543c83ULL;
  static const uint64_t static_value2 = 0x35b9afac2f3e238cULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveTransmissionRequest";
  }

  static const char* value(const  ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string joint\n\
\n\
";
  }

  static const char* value(const  ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveTransmissionResponse";
  }

  static const char* value(const  ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joint);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RemoveTransmissionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RemoveTransmissionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<re2robotModel::RemoveTransmission> {
  static const char* value() 
  {
    return "296066438feec30c8905d1fe1042a90b";
  }

  static const char* value(const re2robotModel::RemoveTransmission&) { return value(); } 
};

template<>
struct DataType<re2robotModel::RemoveTransmission> {
  static const char* value() 
  {
    return "re2robotModel/RemoveTransmission";
  }

  static const char* value(const re2robotModel::RemoveTransmission&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "296066438feec30c8905d1fe1042a90b";
  }

  static const char* value(const re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveTransmission";
  }

  static const char* value(const re2robotModel::RemoveTransmissionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "296066438feec30c8905d1fe1042a90b";
  }

  static const char* value(const re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re2robotModel/RemoveTransmission";
  }

  static const char* value(const re2robotModel::RemoveTransmissionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RE2ROBOTMODEL_SERVICE_REMOVETRANSMISSION_H

